#!/bin/bash
# TGSEC bootstrap — 打开仓库后任意 AI / 人类跑一次即可配齐
# Usage: bash scripts/bootstrap.sh
#        bash scripts/bootstrap.sh --pull
# Marker: .tgsec-bootstrapped  (存在则跳过重活，除非 --force)
#
# @pyufz · @TGSEC-yufeifei 整理

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

FORCE=0
PULL=0
for a in "$@"; do
  case "$a" in
    --force) FORCE=1 ;;
    --pull) PULL=1 ;;
  esac
done

MARKER="$ROOT/.tgsec-bootstrapped"
echo "================================================"
echo "  TGSEC bootstrap"
echo "  root: $ROOT"
echo "================================================"

if [ "$PULL" = 1 ] && [ -d "$ROOT/.git" ]; then
  git pull --ff-only || git pull --rebase || true
fi

# --- project-root auto-load files for every major AI ---
mkdir -p "$ROOT/.claude" "$ROOT/.github/copilot" "$ROOT/.cursor"

# Claude Code: root CLAUDE.md auto-read
if [ -f "$ROOT/ai-config/claude/CLAUDE.md" ]; then
  cp -f "$ROOT/ai-config/claude/CLAUDE.md" "$ROOT/CLAUDE.md"
  cp -f "$ROOT/ai-config/claude/CLAUDE.md" "$ROOT/.claude/CLAUDE.md" 2>/dev/null || true
  echo "[✓] CLAUDE.md (Claude Code / Claude CLI)"
fi

# Cursor
if [ -f "$ROOT/ai-config/cursor/.cursorrules" ]; then
  cp -f "$ROOT/ai-config/cursor/.cursorrules" "$ROOT/.cursorrules"
  mkdir -p "$ROOT/.cursor"
  cp -f "$ROOT/ai-config/cursor/.cursorrules" "$ROOT/.cursor/rules" 2>/dev/null || true
  echo "[✓] .cursorrules (Cursor)"
fi

# Codex / Copilot
if [ -f "$ROOT/ai-config/codex/instructions.md" ]; then
  cp -f "$ROOT/ai-config/codex/instructions.md" "$ROOT/.github/copilot/instructions.md"
  echo "[✓] .github/copilot/instructions.md (Codex)"
fi

# Aider
if [ -f "$ROOT/ai-config/aider/.aider.conf.yml" ]; then
  cp -f "$ROOT/ai-config/aider/.aider.conf.yml" "$ROOT/.aider.conf.yml"
  echo "[✓] .aider.conf.yml (Aider)"
elif [ -f "$ROOT/ai-config/universal/PERSONA.md" ]; then
  # minimal aider conf if missing
  cat > "$ROOT/.aider.conf.yml" <<'YAML'
# TGSEC — generated by bootstrap
read:
  - AGENTS.md
  - MASTER.md
  - CLAUDE.md
YAML
  echo "[✓] .aider.conf.yml (generated)"
fi

# Grok user-level optional
if [ -f "$ROOT/ai-config/grok/system.txt" ]; then
  mkdir -p "$HOME/.grok"
  cp -f "$ROOT/ai-config/grok/system.txt" "$HOME/.grok/system.txt"
  echo "[✓] ~/.grok/system.txt (Grok)"
fi

# OpenCode / generic: AGENTS.md already at root — also copy RULES snapshot
if [ -f "$ROOT/ai-config/universal/RULES.md" ]; then
  cp -f "$ROOT/ai-config/universal/RULES.md" "$ROOT/RULES.md"
  echo "[✓] RULES.md"
fi

# --- 全 AI 技能目录（Claude/Cursor/agents/…）+ Hermes ---
if [ -f "$ROOT/scripts/sync-agent-skills.sh" ]; then
  bash "$ROOT/scripts/sync-agent-skills.sh" || true
  echo "[✓] Agent skills → .claude/skills · ~/.claude/skills · cursor/agents …"
fi
if [ -d "$HOME/.hermes" ]; then
  if [ -f "$ROOT/ai-config/hermes/setup.sh" ]; then
    bash "$ROOT/ai-config/hermes/setup.sh" || true
  fi
  echo "[✓] Hermes memories（技能已由 sync-agent-skills 处理）"
else
  echo "[i] 无 ~/.hermes — 跳过 Hermes memories（正常）"
fi

# --- stamp ---
{
  echo "bootstrapped_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "root=$ROOT"
  echo "host=$(hostname 2>/dev/null || echo unknown)"
} > "$MARKER"

# ensure marker is gitignored
if [ -f "$ROOT/.gitignore" ]; then
  grep -q 'tgsec-bootstrapped' "$ROOT/.gitignore" 2>/dev/null || echo -e "\n.tgsec-bootstrapped\n.tgsec-bootstrapped.*" >> "$ROOT/.gitignore"
else
  echo -e ".tgsec-bootstrapped\n.tgsec-bootstrapped.*\n" > "$ROOT/.gitignore"
fi

echo ""
echo "================================================"
echo "  BOOTSTRAP OK"
echo "================================================"
echo "  知识库: $ROOT/domains + MASTER.md"
echo "  任意 AI 先读: AGENTS.md + ROUTING.md + MASTER.md"
echo "  Claude: CLAUDE.md + .claude/skills | Cursor: .cursorrules + .cursor/skills"
echo "  Hermes: ~/.hermes/skills/security + memories"
echo "  验证: ls domains | head; test -f CLAUDE.md; test -f MASTER.md"
echo "  开新会话后生效（Hermes skill 目录缓存）"
echo ""

# Claude Code: Black-cat pentest-redteam + SessionStart
if [ -x "$ROOT/scripts/ensure-claude-pentest.sh" ]; then
  bash "$ROOT/scripts/ensure-claude-pentest.sh" || true
elif [ -x "$(dirname "$0")/ensure-claude-pentest.sh" ]; then
  bash "$(dirname "$0")/ensure-claude-pentest.sh" || true
fi

